import { buildNotFoundPageMarkup } from '../../../src/components/not-found/not-found-page.js';
import { renderFooterHtml } from '../../../src/layouts/footer-html.js';
import { escapeHtmlAttribute } from '../../../src/layouts/html-output.js';
import { SHARED_TRANSLATION_EXAMPLE } from '../../../examples/manifests/testing-examples.js';

const page = (title: string, content: string, script?: string): string => `<!doctype html>
<!-- Generated by tools/ui-check/codegen-ui-check-cases.ts. Update the fixture, not this file. -->
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${title} - UI Check</title>
    <link rel="stylesheet" href="/src/assets/css/main.css" />
  </head>
  <body>
    <main class="page-shell">
      <p><a href="../">UI Check Workbench</a></p>
      <h1>${title}</h1>
      ${content}
    </main>
    ${script ? `<script type="module" src="${script}"></script>` : ''}
  </body>
</html>
`;

export const renderFooterCase = (): string =>
  page(
    'Footer',
    (
      [
        [
          'full',
          renderFooterHtml({
            id: 'footer-full',
            meta: {
              siteName: 'Rouault',
              siteUrl: '/',
              copyrightText: '© 2026 Ruo Miyata. CC BY 4.0.',
              buildLabel: 'build 4a2b9f1',
            },
            links: [
              { href: '/search/', label: '検索' },
              { href: '/about/', label: 'このサイトについて' },
            ],
          }),
        ],
        [
          'minimal',
          renderFooterHtml({
            id: 'footer-minimal',
            meta: { siteName: 'Rouault', copyrightText: '© 2026 Ruo Miyata. CC BY 4.0.' },
          }),
        ],
        [
          'external',
          renderFooterHtml({
            id: 'footer-external',
            meta: {
              siteName: 'Rouault',
              siteUrl: 'https://rouault.example',
              copyrightText: '© 2026 Ruo Miyata.',
              buildLabel: 'release 2026.03.24',
            },
            links: [
              { href: '/license', label: 'ライセンス' },
              { href: 'mailto:hello@example.com', label: '連絡', external: true },
            ],
            a11y: { navLabel: 'フッター補助導線' },
          }),
        ],
      ] satisfies readonly (readonly [string, string])[]
    )
      .map(
        ([name, markup]) =>
          `<section data-ui-check-footer="${name}"><h2>${name}</h2>${markup}</section>`,
      )
      .join('\n'),
  );

export const renderNotFoundCase = (): string =>
  page(
    'Not found',
    buildNotFoundPageMarkup({
      requestedPath: '/notes/missing-entry?tab=outline#section-2',
    }),
  );

// 実際のproduction componentに入力だけを渡し、shadow/light DOM内部の表示を複製しない。
export const renderReadingInteractionsCase = (): string => {
  const translation = SHARED_TRANSLATION_EXAMPLE;
  const renderTranslation = (id: string, surface: 'popover' | 'drawer'): string => `
    <ui-translation id="${id}" surface="${surface}"
      original="${escapeHtmlAttribute(translation.original)}"
      translated="${escapeHtmlAttribute(translation.translated)}"
      lang="${translation.lang}" target-lang="${translation.targetLang}"></ui-translation>`;
  const renderTabs = (id: string, attributes: string, icons = false): string => `
    <ui-tabs id="${id}" ${attributes}>
      <button slot="tab" value="overview">${icons ? '🏠 ' : ''}概要</button>
      <div slot="panel">概要パネル</div>
      <button slot="tab" value="details">${icons ? '🧪 ' : ''}詳細</button>
      <div slot="panel">詳細パネル</div>
      <button slot="tab" value="settings">${icons ? '⚙️ ' : ''}設定</button>
      <div slot="panel">設定パネル</div>
    </ui-tabs>`;

  return page(
    'Reading interactions',
    `
    <p>production componentの表示・操作感を観察します。正式な合否はbrowser/E2Eテストが所有します。</p>
    <section class="prose" aria-labelledby="tabs-title">
      <h2 id="tabs-title">Tabs</h2>
      <h3>Horizontal</h3>${renderTabs('tabs-horizontal', '')}
      <h3>Initially selected</h3>${renderTabs('tabs-selected', 'default-selected-value="details"')}
      <h3>Vertical</h3>${renderTabs('tabs-vertical', 'orientation="vertical"')}
      <h3>Automatic activation</h3>${renderTabs('tabs-automatic', 'automatic-activation')}
      <h3>Icons</h3>${renderTabs('tabs-icons', '', true)}
    </section>
    <section class="prose" aria-labelledby="translation-title">
      <h2 id="translation-title">Translation</h2>
      <p>Popover: ${renderTranslation('translation-popover', 'popover')}</p>
      <p>Drawer: ${renderTranslation('translation-drawer', 'drawer')}</p>
      <p>二つの訳文を順に開き、単一openの表示も確認できます。</p>
    </section>`,
    '../fixtures/reading-interactions.ts',
  );
};

export const renderVideoCase = (): string => {
  const source = '/src/assets/videos/sample-video.mp4';
  const poster = '/src/assets/images/sample-video-poster.jpg';
  const video = (id: string, caption: string, attributes = ''): string =>
    `<ui-video id="${id}" src="${source}" poster="${poster}" caption="${caption}" ${attributes}></ui-video>`;
  return page(
    'Video',
    `
    <section class="prose" aria-labelledby="video-title">
      <h2 id="video-title">Poster and caption</h2>
      ${video('video-default', 'サンプル動画の代表表示です。')}
      <h2>Captions</h2>
      ${video('video-captions', '字幕付き動画の表示見本です。', 'width="1280" height="720"')}
      <h2>Empty source</h2>
      <ui-video id="video-empty" caption="ソース未設定時の空状態です。"></ui-video>
      <h2>Autoplay / muted / loop</h2>
      ${video('video-autoplay', 'autoplay / muted / loop surface', 'autoplay muted loop playsinline')}
      <p>再生・seek・字幕・fullscreenは各playerで観察します。error/loading/endedの正式な合否はbrowserテストが所有します。</p>
    </section>
    <section aria-labelledby="video-outside-title">
      <h2 id="video-outside-title">Outside prose</h2>
      ${video('video-outside', '標準幅の参照例です。')}
    </section>`,
    '../fixtures/video.ts',
  );
};
