export const DEFAULT_SIDEBAR_ID = 'note-primary';
export const DEFAULT_SIDEBAR_STATE_SCOPE_ID = 'note-navigation';
export const DEFAULT_SIDEBAR_PRESENTATION = 'auto' as const;
export const DEFAULT_SIDEBAR_FIXED_BREAKPOINT = 1024;
export const DEFAULT_SIDEBAR_FIXED_BREAKPOINT_ATTRIBUTE = String(DEFAULT_SIDEBAR_FIXED_BREAKPOINT);
export const DEFAULT_SIDEBAR_FIXED_MEDIA_QUERY = `(min-width: ${String(DEFAULT_SIDEBAR_FIXED_BREAKPOINT)}px)`;
