import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { createStaticRenderIdContext } from '../../shared/static-render-id-context.js';
import { renderSearchPageHtml } from '../../src/layouts/search-page-html.js';
import { searchPageFixture } from './fixtures/search-page-fixture.js';

const generatedComment =
  '<!-- Generated by tools/ui-check/codegen-ui-check-cases.ts. Do not edit by hand; update the fixture or generator instead. -->';

const filterDetailsStartTagRe =
  /<details\b(?=[^>]*\bclass="(?:[^"]*\s)?filter-details(?:\s[^"]*)?")[^>]*>/gu;

const normalizeGeneratedHtml = (html: string): string => html.replace(/[ \t]+$/gmu, '');

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const searchControlsPath = path.join(__dirname, 'cases', 'search-controls.html');

const createOpenFilterDetailsVariant = (html: string): string => {
  const matches = [...html.matchAll(filterDetailsStartTagRe)];
  if (matches.length !== 1) {
    throw new Error(
      `Expected exactly one details.filter-details element, but found ${matches.length.toString()}.`,
    );
  }

  const match = matches[0];
  if (match === undefined) {
    throw new Error('Failed to read details.filter-details match.');
  }
  const startTag = match[0];
  if (startTag.length === 0) {
    throw new Error('Failed to read details.filter-details start tag.');
  }
  if (/\sopen(?:\s|>|=)/u.test(startTag)) {
    return html;
  }

  const openStartTag = startTag.replace(/>$/u, ' open>');
  return `${html.slice(0, match.index)}${openStartTag}${html.slice(match.index + startTag.length)}`;
};

const renderSearchControlsCase = (): string => {
  const renderedSearchPage = renderSearchPageHtml({
    initialState: searchPageFixture.initialState,
    initialResponse: searchPageFixture.initialResponse,
    siteUrlContext: searchPageFixture.siteUrlContext,
    idContext: createStaticRenderIdContext('ui-check:search-controls'),
  });

  const openVariant = createOpenFilterDetailsVariant(renderedSearchPage);

  return `<!doctype html>
${generatedComment}
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Search controls - UI Check</title>
    <link rel="stylesheet" href="/src/assets/css/main.css" />
  </head>
  <body>
    <main>
      <p><a href="../">UI Check Workbench</a></p>
      ${openVariant}
    </main>
  </body>
</html>
`;
};

const writeIfChanged = async (filePath: string, content: string): Promise<void> => {
  let current: string | null = null;
  try {
    current = await readFile(filePath, 'utf8');
  } catch (error) {
    if (!(error instanceof Error) || !('code' in error) || error.code !== 'ENOENT') {
      throw error;
    }
  }

  if (current === content) {
    return;
  }

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, 'utf8');
};

await writeIfChanged(searchControlsPath, normalizeGeneratedHtml(renderSearchControlsCase()));
