export const ROUTER_DOCUMENT_HOST_ANNOUNCEMENT_ATTRIBUTE = 'data-router-document-host-announcement';
export const ROUTER_DOCUMENT_HOST_ANNOUNCEMENT_SELECTOR = `[${ROUTER_DOCUMENT_HOST_ANNOUNCEMENT_ATTRIBUTE}]`;
export const ROUTER_DOCUMENT_HOST_ANNOUNCEMENT_ARIA_LIVE = 'polite';
export const ROUTER_DOCUMENT_HOST_ANNOUNCEMENT_ARIA_ATOMIC = 'true';
export const ROUTER_DOCUMENT_HOST_ANNOUNCEMENT_CLASS_NAME = 'sr-only';
