export {
  DEFAULT_SIDEBAR_FIXED_BREAKPOINT as NOTE_SIDEBAR_FIXED_BREAKPOINT,
  DEFAULT_SIDEBAR_FIXED_BREAKPOINT_ATTRIBUTE as NOTE_SIDEBAR_FIXED_BREAKPOINT_ATTRIBUTE,
  DEFAULT_SIDEBAR_FIXED_MEDIA_QUERY as NOTE_SIDEBAR_FIXED_MEDIA_QUERY,
} from '../../shared/navigation/sidebar-shell-defaults.js';
