export const NOTE_SIDEBAR_FIXED_BREAKPOINT = 1024;
export const NOTE_SIDEBAR_FIXED_BREAKPOINT_ATTRIBUTE = String(NOTE_SIDEBAR_FIXED_BREAKPOINT);
export const NOTE_SIDEBAR_FIXED_MEDIA_QUERY = `(min-width: ${String(NOTE_SIDEBAR_FIXED_BREAKPOINT)}px)`;
